package CJQT6.gui

// GUI布局相关类型定义
// TODO: 后续添加布局类封装

// 对齐方式
public const AlignLeft: Int32 = 0x0001
public const AlignRight: Int32 = 0x0002
public const AlignHCenter: Int32 = 0x0004
public const AlignTop: Int32 = 0x0020
public const AlignBottom: Int32 = 0x0040
public const AlignVCenter: Int32 = 0x0080
public const AlignCenter: Int32 = 0x0004 | 0x0080

// 方向
public const Horizontal: Int32 = 1
public const Vertical: Int32 = 2
