[package]
  cjc-version = "1.0.5"
  name = "CJQT6"
  description = "仓颉语言的Qt6封装库"
  version = "1.0.0"
  target-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = "-L/home/yuan123/cangjiecode/CJQT6/native/build/lib -lcjqt6_bridge"
  package-configuration = {}

[dependencies]