[package]
  cjc-version = "1.0.5"
  name = "music_player"
  description = "CJQT6 音乐播放器示例"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = "-L/home/yuan123/cangjiecode/CJQT6/native/build/lib -lcjqt6_bridge"
  package-configuration = {}

[dependencies]
  CJQT6 = { path = "../../" }
