[package]
  cjc-version = "1.0.5"
  name = "qml_test"
  description = "CJQT6 QML 测试示例"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = "-LC:/CodeTools/cangjie_git/CJQT6/test_deploy -lcjqt6_bridge"
  package-configuration = {}


[dependencies]
  CJQT6 = { path = "../../" }