[package]
  cjc-version = "1.1.0"
  name = "hello_cjqt6"
  description = "CJQT6 最小演示实例 - Hello CJQT6"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = "-L../../releases/windows-x64 -lcjqt6_bridge"
  package-configuration = {}

[dependencies]
  cjqt6 = { path = "../../" }
