[package]
  cjc-version = "1.1.0"
  name = "qml_demo"
  organization = ""
  description = "CJQT6 QML Demo"
  version = "1.0.0"
  output-type = "executable"
  link-option = "-L/home/yuan123/cangjiecode/CJQT6/native/build/lib -lcjqt6_bridge"

[dependencies]
  CJQT6 = {path = "../../"}