[package]
  cjc-version = "1.0.5"
  name = "expense_tracker"
  description = "CJQT6 个人记账本示例"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = "-lcjqt6_bridge -L../../releases/windows-x64"
  package-configuration = {}

[dependencies]
  cjqt6 = { path = "../../" }
